/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderSettingsRouteImport } from './routes/provider/settings'
import { Route as ProviderOrdersRouteImport } from './routes/provider/orders'
import { Route as ProviderEarningsRouteImport } from './routes/provider/earnings'
import { Route as ProviderDashboardRouteImport } from './routes/provider/dashboard'
import { Route as ProviderBookingsRouteImport } from './routes/provider/bookings'
import { Route as FarmerSettingsRouteImport } from './routes/farmer/settings'
import { Route as FarmerHelpRouteImport } from './routes/farmer/help'
import { Route as FarmerDashboardRouteImport } from './routes/farmer/dashboard'
import { Route as FarmerCheckoutRouteImport } from './routes/farmer/checkout'
import { Route as FarmerCartRouteImport } from './routes/farmer/cart'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminServiceProvidersRouteImport } from './routes/admin/service-providers'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as ProviderServicesIndexRouteImport } from './routes/provider/services/index'
import { Route as ProviderProductsIndexRouteImport } from './routes/provider/products/index'
import { Route as FarmerServicesIndexRouteImport } from './routes/farmer/services/index'
import { Route as FarmerProductsIndexRouteImport } from './routes/farmer/products/index'
import { Route as FarmerOrdersIndexRouteImport } from './routes/farmer/orders/index'
import { Route as FarmerBookingsIndexRouteImport } from './routes/farmer/bookings/index'
import { Route as ProviderServicesAddRouteImport } from './routes/provider/services/add'
import { Route as ProviderProductsAddRouteImport } from './routes/provider/products/add'
import { Route as FarmerSettingsPersonalRouteImport } from './routes/farmer/settings.personal'
import { Route as FarmerSettingsAddressesRouteImport } from './routes/farmer/settings.addresses'
import { Route as FarmerServicesServiceIdRouteImport } from './routes/farmer/services/$serviceId'
import { Route as FarmerProductsProductIdRouteImport } from './routes/farmer/products.$productId'
import { Route as FarmerOrdersOrderIdRouteImport } from './routes/farmer/orders.$orderId'
import { Route as ProviderServicesEditServiceIdRouteImport } from './routes/provider/services/edit.$serviceId'
import { Route as ProviderProductsEditProductIdRouteImport } from './routes/provider/products/edit.$productId'
import { Route as FarmerServicesServiceIdBookRouteImport } from './routes/farmer/services.$serviceId.book'
import { Route as FarmerBookingsBookingIdTrackingRouteImport } from './routes/farmer/bookings.$bookingId.tracking'

const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderSettingsRoute = ProviderSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderOrdersRoute = ProviderOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderEarningsRoute = ProviderEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderDashboardRoute = ProviderDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderBookingsRoute = ProviderBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ProviderRoute,
} as any)
const FarmerSettingsRoute = FarmerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerHelpRoute = FarmerHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerDashboardRoute = FarmerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerCheckoutRoute = FarmerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerCartRoute = FarmerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => FarmerRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiceProvidersRoute = AdminServiceProvidersRouteImport.update({
  id: '/service-providers',
  path: '/service-providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const ProviderServicesIndexRoute = ProviderServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderProductsIndexRoute = ProviderProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => ProviderRoute,
} as any)
const FarmerServicesIndexRoute = FarmerServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProductsIndexRoute = FarmerProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerOrdersIndexRoute = FarmerOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerBookingsIndexRoute = FarmerBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => FarmerRoute,
} as any)
const ProviderServicesAddRoute = ProviderServicesAddRouteImport.update({
  id: '/services/add',
  path: '/services/add',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderProductsAddRoute = ProviderProductsAddRouteImport.update({
  id: '/products/add',
  path: '/products/add',
  getParentRoute: () => ProviderRoute,
} as any)
const FarmerSettingsPersonalRoute = FarmerSettingsPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => FarmerSettingsRoute,
} as any)
const FarmerSettingsAddressesRoute = FarmerSettingsAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => FarmerSettingsRoute,
} as any)
const FarmerServicesServiceIdRoute = FarmerServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProductsProductIdRoute = FarmerProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerOrdersOrderIdRoute = FarmerOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => FarmerRoute,
} as any)
const ProviderServicesEditServiceIdRoute =
  ProviderServicesEditServiceIdRouteImport.update({
    id: '/services/edit/$serviceId',
    path: '/services/edit/$serviceId',
    getParentRoute: () => ProviderRoute,
  } as any)
const ProviderProductsEditProductIdRoute =
  ProviderProductsEditProductIdRouteImport.update({
    id: '/products/edit/$productId',
    path: '/products/edit/$productId',
    getParentRoute: () => ProviderRoute,
  } as any)
const FarmerServicesServiceIdBookRoute =
  FarmerServicesServiceIdBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => FarmerServicesServiceIdRoute,
  } as any)
const FarmerBookingsBookingIdTrackingRoute =
  FarmerBookingsBookingIdTrackingRouteImport.update({
    id: '/bookings/$bookingId/tracking',
    path: '/bookings/$bookingId/tracking',
    getParentRoute: () => FarmerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/provider': typeof ProviderRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/service-providers': typeof AdminServiceProvidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/farmer/cart': typeof FarmerCartRoute
  '/farmer/checkout': typeof FarmerCheckoutRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/help': typeof FarmerHelpRoute
  '/farmer/settings': typeof FarmerSettingsRouteWithChildren
  '/provider/bookings': typeof ProviderBookingsRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/provider/earnings': typeof ProviderEarningsRoute
  '/provider/orders': typeof ProviderOrdersRoute
  '/provider/settings': typeof ProviderSettingsRoute
  '/farmer/orders/$orderId': typeof FarmerOrdersOrderIdRoute
  '/farmer/products/$productId': typeof FarmerProductsProductIdRoute
  '/farmer/services/$serviceId': typeof FarmerServicesServiceIdRouteWithChildren
  '/farmer/settings/addresses': typeof FarmerSettingsAddressesRoute
  '/farmer/settings/personal': typeof FarmerSettingsPersonalRoute
  '/provider/products/add': typeof ProviderProductsAddRoute
  '/provider/services/add': typeof ProviderServicesAddRoute
  '/farmer/bookings/': typeof FarmerBookingsIndexRoute
  '/farmer/orders/': typeof FarmerOrdersIndexRoute
  '/farmer/products/': typeof FarmerProductsIndexRoute
  '/farmer/services/': typeof FarmerServicesIndexRoute
  '/provider/products/': typeof ProviderProductsIndexRoute
  '/provider/services/': typeof ProviderServicesIndexRoute
  '/farmer/bookings/$bookingId/tracking': typeof FarmerBookingsBookingIdTrackingRoute
  '/farmer/services/$serviceId/book': typeof FarmerServicesServiceIdBookRoute
  '/provider/products/edit/$productId': typeof ProviderProductsEditProductIdRoute
  '/provider/services/edit/$serviceId': typeof ProviderServicesEditServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/provider': typeof ProviderRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/service-providers': typeof AdminServiceProvidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/farmer/cart': typeof FarmerCartRoute
  '/farmer/checkout': typeof FarmerCheckoutRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/help': typeof FarmerHelpRoute
  '/farmer/settings': typeof FarmerSettingsRouteWithChildren
  '/provider/bookings': typeof ProviderBookingsRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/provider/earnings': typeof ProviderEarningsRoute
  '/provider/orders': typeof ProviderOrdersRoute
  '/provider/settings': typeof ProviderSettingsRoute
  '/farmer/orders/$orderId': typeof FarmerOrdersOrderIdRoute
  '/farmer/products/$productId': typeof FarmerProductsProductIdRoute
  '/farmer/services/$serviceId': typeof FarmerServicesServiceIdRouteWithChildren
  '/farmer/settings/addresses': typeof FarmerSettingsAddressesRoute
  '/farmer/settings/personal': typeof FarmerSettingsPersonalRoute
  '/provider/products/add': typeof ProviderProductsAddRoute
  '/provider/services/add': typeof ProviderServicesAddRoute
  '/farmer/bookings': typeof FarmerBookingsIndexRoute
  '/farmer/orders': typeof FarmerOrdersIndexRoute
  '/farmer/products': typeof FarmerProductsIndexRoute
  '/farmer/services': typeof FarmerServicesIndexRoute
  '/provider/products': typeof ProviderProductsIndexRoute
  '/provider/services': typeof ProviderServicesIndexRoute
  '/farmer/bookings/$bookingId/tracking': typeof FarmerBookingsBookingIdTrackingRoute
  '/farmer/services/$serviceId/book': typeof FarmerServicesServiceIdBookRoute
  '/provider/products/edit/$productId': typeof ProviderProductsEditProductIdRoute
  '/provider/services/edit/$serviceId': typeof ProviderServicesEditServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/provider': typeof ProviderRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/service-providers': typeof AdminServiceProvidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/farmer/cart': typeof FarmerCartRoute
  '/farmer/checkout': typeof FarmerCheckoutRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/help': typeof FarmerHelpRoute
  '/farmer/settings': typeof FarmerSettingsRouteWithChildren
  '/provider/bookings': typeof ProviderBookingsRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/provider/earnings': typeof ProviderEarningsRoute
  '/provider/orders': typeof ProviderOrdersRoute
  '/provider/settings': typeof ProviderSettingsRoute
  '/farmer/orders/$orderId': typeof FarmerOrdersOrderIdRoute
  '/farmer/products/$productId': typeof FarmerProductsProductIdRoute
  '/farmer/services/$serviceId': typeof FarmerServicesServiceIdRouteWithChildren
  '/farmer/settings/addresses': typeof FarmerSettingsAddressesRoute
  '/farmer/settings/personal': typeof FarmerSettingsPersonalRoute
  '/provider/products/add': typeof ProviderProductsAddRoute
  '/provider/services/add': typeof ProviderServicesAddRoute
  '/farmer/bookings/': typeof FarmerBookingsIndexRoute
  '/farmer/orders/': typeof FarmerOrdersIndexRoute
  '/farmer/products/': typeof FarmerProductsIndexRoute
  '/farmer/services/': typeof FarmerServicesIndexRoute
  '/provider/products/': typeof ProviderProductsIndexRoute
  '/provider/services/': typeof ProviderServicesIndexRoute
  '/farmer/bookings/$bookingId/tracking': typeof FarmerBookingsBookingIdTrackingRoute
  '/farmer/services/$serviceId/book': typeof FarmerServicesServiceIdBookRoute
  '/provider/products/edit/$productId': typeof ProviderProductsEditProductIdRoute
  '/provider/services/edit/$serviceId': typeof ProviderServicesEditServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/farmer'
    | '/provider'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/service-providers'
    | '/admin/settings'
    | '/auth/login'
    | '/auth/register'
    | '/farmer/cart'
    | '/farmer/checkout'
    | '/farmer/dashboard'
    | '/farmer/help'
    | '/farmer/settings'
    | '/provider/bookings'
    | '/provider/dashboard'
    | '/provider/earnings'
    | '/provider/orders'
    | '/provider/settings'
    | '/farmer/orders/$orderId'
    | '/farmer/products/$productId'
    | '/farmer/services/$serviceId'
    | '/farmer/settings/addresses'
    | '/farmer/settings/personal'
    | '/provider/products/add'
    | '/provider/services/add'
    | '/farmer/bookings/'
    | '/farmer/orders/'
    | '/farmer/products/'
    | '/farmer/services/'
    | '/provider/products/'
    | '/provider/services/'
    | '/farmer/bookings/$bookingId/tracking'
    | '/farmer/services/$serviceId/book'
    | '/provider/products/edit/$productId'
    | '/provider/services/edit/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/farmer'
    | '/provider'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/service-providers'
    | '/admin/settings'
    | '/auth/login'
    | '/auth/register'
    | '/farmer/cart'
    | '/farmer/checkout'
    | '/farmer/dashboard'
    | '/farmer/help'
    | '/farmer/settings'
    | '/provider/bookings'
    | '/provider/dashboard'
    | '/provider/earnings'
    | '/provider/orders'
    | '/provider/settings'
    | '/farmer/orders/$orderId'
    | '/farmer/products/$productId'
    | '/farmer/services/$serviceId'
    | '/farmer/settings/addresses'
    | '/farmer/settings/personal'
    | '/provider/products/add'
    | '/provider/services/add'
    | '/farmer/bookings'
    | '/farmer/orders'
    | '/farmer/products'
    | '/farmer/services'
    | '/provider/products'
    | '/provider/services'
    | '/farmer/bookings/$bookingId/tracking'
    | '/farmer/services/$serviceId/book'
    | '/provider/products/edit/$productId'
    | '/provider/services/edit/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/farmer'
    | '/provider'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/service-providers'
    | '/admin/settings'
    | '/auth/login'
    | '/auth/register'
    | '/farmer/cart'
    | '/farmer/checkout'
    | '/farmer/dashboard'
    | '/farmer/help'
    | '/farmer/settings'
    | '/provider/bookings'
    | '/provider/dashboard'
    | '/provider/earnings'
    | '/provider/orders'
    | '/provider/settings'
    | '/farmer/orders/$orderId'
    | '/farmer/products/$productId'
    | '/farmer/services/$serviceId'
    | '/farmer/settings/addresses'
    | '/farmer/settings/personal'
    | '/provider/products/add'
    | '/provider/services/add'
    | '/farmer/bookings/'
    | '/farmer/orders/'
    | '/farmer/products/'
    | '/farmer/services/'
    | '/provider/products/'
    | '/provider/services/'
    | '/farmer/bookings/$bookingId/tracking'
    | '/farmer/services/$serviceId/book'
    | '/provider/products/edit/$productId'
    | '/provider/services/edit/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  FarmerRoute: typeof FarmerRouteWithChildren
  ProviderRoute: typeof ProviderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/settings': {
      id: '/provider/settings'
      path: '/settings'
      fullPath: '/provider/settings'
      preLoaderRoute: typeof ProviderSettingsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/orders': {
      id: '/provider/orders'
      path: '/orders'
      fullPath: '/provider/orders'
      preLoaderRoute: typeof ProviderOrdersRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/earnings': {
      id: '/provider/earnings'
      path: '/earnings'
      fullPath: '/provider/earnings'
      preLoaderRoute: typeof ProviderEarningsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/dashboard': {
      id: '/provider/dashboard'
      path: '/dashboard'
      fullPath: '/provider/dashboard'
      preLoaderRoute: typeof ProviderDashboardRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/bookings': {
      id: '/provider/bookings'
      path: '/bookings'
      fullPath: '/provider/bookings'
      preLoaderRoute: typeof ProviderBookingsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/farmer/settings': {
      id: '/farmer/settings'
      path: '/settings'
      fullPath: '/farmer/settings'
      preLoaderRoute: typeof FarmerSettingsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/help': {
      id: '/farmer/help'
      path: '/help'
      fullPath: '/farmer/help'
      preLoaderRoute: typeof FarmerHelpRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/dashboard': {
      id: '/farmer/dashboard'
      path: '/dashboard'
      fullPath: '/farmer/dashboard'
      preLoaderRoute: typeof FarmerDashboardRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/checkout': {
      id: '/farmer/checkout'
      path: '/checkout'
      fullPath: '/farmer/checkout'
      preLoaderRoute: typeof FarmerCheckoutRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/cart': {
      id: '/farmer/cart'
      path: '/cart'
      fullPath: '/farmer/cart'
      preLoaderRoute: typeof FarmerCartRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-providers': {
      id: '/admin/service-providers'
      path: '/service-providers'
      fullPath: '/admin/service-providers'
      preLoaderRoute: typeof AdminServiceProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/provider/services/': {
      id: '/provider/services/'
      path: '/services'
      fullPath: '/provider/services/'
      preLoaderRoute: typeof ProviderServicesIndexRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/products/': {
      id: '/provider/products/'
      path: '/products'
      fullPath: '/provider/products/'
      preLoaderRoute: typeof ProviderProductsIndexRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/farmer/services/': {
      id: '/farmer/services/'
      path: '/services'
      fullPath: '/farmer/services/'
      preLoaderRoute: typeof FarmerServicesIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/products/': {
      id: '/farmer/products/'
      path: '/products'
      fullPath: '/farmer/products/'
      preLoaderRoute: typeof FarmerProductsIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/orders/': {
      id: '/farmer/orders/'
      path: '/orders'
      fullPath: '/farmer/orders/'
      preLoaderRoute: typeof FarmerOrdersIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/bookings/': {
      id: '/farmer/bookings/'
      path: '/bookings'
      fullPath: '/farmer/bookings/'
      preLoaderRoute: typeof FarmerBookingsIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/provider/services/add': {
      id: '/provider/services/add'
      path: '/services/add'
      fullPath: '/provider/services/add'
      preLoaderRoute: typeof ProviderServicesAddRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/products/add': {
      id: '/provider/products/add'
      path: '/products/add'
      fullPath: '/provider/products/add'
      preLoaderRoute: typeof ProviderProductsAddRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/farmer/settings/personal': {
      id: '/farmer/settings/personal'
      path: '/personal'
      fullPath: '/farmer/settings/personal'
      preLoaderRoute: typeof FarmerSettingsPersonalRouteImport
      parentRoute: typeof FarmerSettingsRoute
    }
    '/farmer/settings/addresses': {
      id: '/farmer/settings/addresses'
      path: '/addresses'
      fullPath: '/farmer/settings/addresses'
      preLoaderRoute: typeof FarmerSettingsAddressesRouteImport
      parentRoute: typeof FarmerSettingsRoute
    }
    '/farmer/services/$serviceId': {
      id: '/farmer/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/farmer/services/$serviceId'
      preLoaderRoute: typeof FarmerServicesServiceIdRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/products/$productId': {
      id: '/farmer/products/$productId'
      path: '/products/$productId'
      fullPath: '/farmer/products/$productId'
      preLoaderRoute: typeof FarmerProductsProductIdRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/orders/$orderId': {
      id: '/farmer/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/farmer/orders/$orderId'
      preLoaderRoute: typeof FarmerOrdersOrderIdRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/provider/services/edit/$serviceId': {
      id: '/provider/services/edit/$serviceId'
      path: '/services/edit/$serviceId'
      fullPath: '/provider/services/edit/$serviceId'
      preLoaderRoute: typeof ProviderServicesEditServiceIdRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/products/edit/$productId': {
      id: '/provider/products/edit/$productId'
      path: '/products/edit/$productId'
      fullPath: '/provider/products/edit/$productId'
      preLoaderRoute: typeof ProviderProductsEditProductIdRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/farmer/services/$serviceId/book': {
      id: '/farmer/services/$serviceId/book'
      path: '/book'
      fullPath: '/farmer/services/$serviceId/book'
      preLoaderRoute: typeof FarmerServicesServiceIdBookRouteImport
      parentRoute: typeof FarmerServicesServiceIdRoute
    }
    '/farmer/bookings/$bookingId/tracking': {
      id: '/farmer/bookings/$bookingId/tracking'
      path: '/bookings/$bookingId/tracking'
      fullPath: '/farmer/bookings/$bookingId/tracking'
      preLoaderRoute: typeof FarmerBookingsBookingIdTrackingRouteImport
      parentRoute: typeof FarmerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminServiceProvidersRoute: typeof AdminServiceProvidersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminServiceProvidersRoute: AdminServiceProvidersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface FarmerSettingsRouteChildren {
  FarmerSettingsAddressesRoute: typeof FarmerSettingsAddressesRoute
  FarmerSettingsPersonalRoute: typeof FarmerSettingsPersonalRoute
}

const FarmerSettingsRouteChildren: FarmerSettingsRouteChildren = {
  FarmerSettingsAddressesRoute: FarmerSettingsAddressesRoute,
  FarmerSettingsPersonalRoute: FarmerSettingsPersonalRoute,
}

const FarmerSettingsRouteWithChildren = FarmerSettingsRoute._addFileChildren(
  FarmerSettingsRouteChildren,
)

interface FarmerServicesServiceIdRouteChildren {
  FarmerServicesServiceIdBookRoute: typeof FarmerServicesServiceIdBookRoute
}

const FarmerServicesServiceIdRouteChildren: FarmerServicesServiceIdRouteChildren =
  {
    FarmerServicesServiceIdBookRoute: FarmerServicesServiceIdBookRoute,
  }

const FarmerServicesServiceIdRouteWithChildren =
  FarmerServicesServiceIdRoute._addFileChildren(
    FarmerServicesServiceIdRouteChildren,
  )

interface FarmerRouteChildren {
  FarmerCartRoute: typeof FarmerCartRoute
  FarmerCheckoutRoute: typeof FarmerCheckoutRoute
  FarmerDashboardRoute: typeof FarmerDashboardRoute
  FarmerHelpRoute: typeof FarmerHelpRoute
  FarmerSettingsRoute: typeof FarmerSettingsRouteWithChildren
  FarmerOrdersOrderIdRoute: typeof FarmerOrdersOrderIdRoute
  FarmerProductsProductIdRoute: typeof FarmerProductsProductIdRoute
  FarmerServicesServiceIdRoute: typeof FarmerServicesServiceIdRouteWithChildren
  FarmerBookingsIndexRoute: typeof FarmerBookingsIndexRoute
  FarmerOrdersIndexRoute: typeof FarmerOrdersIndexRoute
  FarmerProductsIndexRoute: typeof FarmerProductsIndexRoute
  FarmerServicesIndexRoute: typeof FarmerServicesIndexRoute
  FarmerBookingsBookingIdTrackingRoute: typeof FarmerBookingsBookingIdTrackingRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerCartRoute: FarmerCartRoute,
  FarmerCheckoutRoute: FarmerCheckoutRoute,
  FarmerDashboardRoute: FarmerDashboardRoute,
  FarmerHelpRoute: FarmerHelpRoute,
  FarmerSettingsRoute: FarmerSettingsRouteWithChildren,
  FarmerOrdersOrderIdRoute: FarmerOrdersOrderIdRoute,
  FarmerProductsProductIdRoute: FarmerProductsProductIdRoute,
  FarmerServicesServiceIdRoute: FarmerServicesServiceIdRouteWithChildren,
  FarmerBookingsIndexRoute: FarmerBookingsIndexRoute,
  FarmerOrdersIndexRoute: FarmerOrdersIndexRoute,
  FarmerProductsIndexRoute: FarmerProductsIndexRoute,
  FarmerServicesIndexRoute: FarmerServicesIndexRoute,
  FarmerBookingsBookingIdTrackingRoute: FarmerBookingsBookingIdTrackingRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

interface ProviderRouteChildren {
  ProviderBookingsRoute: typeof ProviderBookingsRoute
  ProviderDashboardRoute: typeof ProviderDashboardRoute
  ProviderEarningsRoute: typeof ProviderEarningsRoute
  ProviderOrdersRoute: typeof ProviderOrdersRoute
  ProviderSettingsRoute: typeof ProviderSettingsRoute
  ProviderProductsAddRoute: typeof ProviderProductsAddRoute
  ProviderServicesAddRoute: typeof ProviderServicesAddRoute
  ProviderProductsIndexRoute: typeof ProviderProductsIndexRoute
  ProviderServicesIndexRoute: typeof ProviderServicesIndexRoute
  ProviderProductsEditProductIdRoute: typeof ProviderProductsEditProductIdRoute
  ProviderServicesEditServiceIdRoute: typeof ProviderServicesEditServiceIdRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderBookingsRoute: ProviderBookingsRoute,
  ProviderDashboardRoute: ProviderDashboardRoute,
  ProviderEarningsRoute: ProviderEarningsRoute,
  ProviderOrdersRoute: ProviderOrdersRoute,
  ProviderSettingsRoute: ProviderSettingsRoute,
  ProviderProductsAddRoute: ProviderProductsAddRoute,
  ProviderServicesAddRoute: ProviderServicesAddRoute,
  ProviderProductsIndexRoute: ProviderProductsIndexRoute,
  ProviderServicesIndexRoute: ProviderServicesIndexRoute,
  ProviderProductsEditProductIdRoute: ProviderProductsEditProductIdRoute,
  ProviderServicesEditServiceIdRoute: ProviderServicesEditServiceIdRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  FarmerRoute: FarmerRouteWithChildren,
  ProviderRoute: ProviderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
